[package]
name = "webrender-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
gleam = "0.13.0"
glutin = "0.29.0"
webrender = { git = "https://github.com/servo/webrender" }
